"""Change the id type of candidate_exp

Revision ID: 3b1b5c14cdca
Revises: 895327de526f
Create Date: 2026-07-14 16:16:17.882838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b5c14cdca'
down_revision: Union[str, Sequence[str], None] = '895327de526f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_experience')
    op.create_table('candidate_experience',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('candidate_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('organisation', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('details', sa.String(length=2000), nullable=False),
        sa.Column('skills_used', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
        sa.Column('evidence_link', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name='fk_candidate_experience_candidate_id'),
        sa.PrimaryKeyConstraint('id', name='pk_candidate_experience'),
    )
    op.create_index('ix_candidate_experience_id', 'candidate_experience', ['id'])
    op.create_index('ix_candidate_experience_candidate_id', 'candidate_experience', ['candidate_id'])
    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_experience_id'), table_name='candidate_experience')
    op.alter_column('candidate_experience', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
