"""Added new column for Job Posting

Revision ID: 8688a70de93e
Revises: 5ad8c01b8bf9
Create Date: 2026-07-18 22:18:17.805128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8688a70de93e'
down_revision: Union[str, Sequence[str], None] = '5ad8c01b8bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting', sa.Column('avg_match', sa.Float(), nullable=True))
    op.add_column('job_posting', sa.Column('top_candidate_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'job_posting', 'candidate', ['top_candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posting', type_='foreignkey')
    op.drop_column('job_posting', 'top_candidate_id')
    op.drop_column('job_posting', 'avg_match')
    # ### end Alembic commands ###
