"""Add new columns and ENUM values for Users

Revision ID: 895327de526f
Revises: becad2cdb7ca
Create Date: 2026-07-13 20:46:13.074324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895327de526f'
down_revision: Union[str, Sequence[str], None] = 'becad2cdb7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
     # 1. Add a temp column with the new type
    op.execute("""
        ALTER TABLE users
        ADD COLUMN role_new VARCHAR(50)
    """)

    # 2. Copy + remap values
    op.execute("""
        UPDATE users SET role_new = CASE
            WHEN role::text = 'student' THEN 'candidate'
            ELSE role::text
        END
    """)

    # 3. Drop old column
    op.execute("ALTER TABLE users DROP COLUMN role")

    # 4. Drop old enum type
    op.execute("DROP TYPE user_role_enum")

    # 5. Recreate enum with new values
    op.execute("""
        CREATE TYPE user_role_enum AS ENUM
        ('candidate', 'employer', 'university')
    """)

    # 6. Add new column with correct type
    op.execute("""
        ALTER TABLE users
        ADD COLUMN role user_role_enum NOT NULL DEFAULT 'candidate'
    """)

    # 7. Populate from temp column
    op.execute("""
        UPDATE users SET role = role_new::user_role_enum
    """)

    # 8. Drop temp column
    op.execute("ALTER TABLE users DROP COLUMN role_new")

    # 9. Remove the default (optional, enforce at app layer)
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    
    op.create_table('candidate_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('organisation', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('details', sa.String(length=2000), nullable=False),
    sa.Column('skills_used', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experience_candidate_id'), 'candidate_experience', ['candidate_id'], unique=False)
    op.add_column('candidate', sa.Column('status', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
     # Reverse the rename
    op.execute("""
        ALTER TABLE users
        ADD COLUMN role_old VARCHAR(50)
    """)
    op.execute("""
        UPDATE users SET role_old = CASE
            WHEN role::text = 'candidate' THEN 'student'
            ELSE role::text
        END
    """)
    op.execute("ALTER TABLE users DROP COLUMN role")
    op.execute("DROP TYPE user_role_enum")
    op.execute("""
        CREATE TYPE user_role_enum AS ENUM
        ('student', 'employer', 'university')
    """)
    op.execute("""
        ALTER TABLE users
        ADD COLUMN role user_role_enum NOT NULL DEFAULT 'student'
    """)
    op.execute("UPDATE users SET role = role_old::user_role_enum")
    op.execute("ALTER TABLE users DROP COLUMN role_old")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    
    op.drop_column('candidate', 'status')
    op.drop_index(op.f('ix_candidate_experience_candidate_id'), table_name='candidate_experience')
    op.drop_table('candidate_experience')
    # ### end Alembic commands ###
