"""add status column

Revision ID: a8f82e533a27
Revises: 3b1b5c14cdca
Create Date: 2026-07-14 18:46:22.177818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f82e533a27'
down_revision: Union[str, Sequence[str], None] = '3b1b5c14cdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'status',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'status',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
