"""added new table and columns

Revision ID: becad2cdb7ca
Revises: c15d0727d68e
Create Date: 2026-07-10 16:37:46.555295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becad2cdb7ca'
down_revision: Union[str, Sequence[str], None] = 'c15d0727d68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the integer sequence default first
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")

    # Now alter the type
    op.alter_column('users', 'id',
                existing_type=sa.INTEGER(),
                type_=sa.UUID(),
                existing_nullable=False,
                postgresql_using='gen_random_uuid()')

    # Set the new UUID default
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.create_table('company_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('num_of_employee', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('ssm_id', sa.String(length=100), nullable=False),
    sa.Column('logo_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=1500), nullable=False),
    sa.Column('minSalary', sa.Integer(), nullable=True),
    sa.Column('maxSalary', sa.Integer(), nullable=True),
    sa.Column('application_num', sa.Integer(), nullable=False),
    sa.Column('view_num', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiredAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('num_of_student', sa.Integer(), nullable=False),
    sa.Column('num_of_faculties', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_user_id'), 'candidate', ['user_id'], unique=False)
    op.create_table('employer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_company_id'), 'employer', ['company_id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['last_name'])
    op.create_unique_constraint(None, 'users', ['first_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_employer_company_id'), table_name='employer')
    op.drop_table('employer')
    op.drop_index(op.f('ix_candidate_user_id'), table_name='candidate')
    op.drop_table('candidate')
    op.drop_table('university_profile')
    op.drop_table('job_posting')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
