"""set nullable for candidate id

Revision ID: fc5db5ea7234
Revises: 8fcaedd3ec53
Create Date: 2026-07-15 12:07:38.069876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5db5ea7234'
down_revision: Union[str, Sequence[str], None] = '8fcaedd3ec53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_experience', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_experience', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
