"""added a role column for user

Revision ID: fd7ef9030846
Revises: 11e31a447969
Create Date: 2026-07-06 19:56:09.003275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7ef9030846'
down_revision: Union[str, Sequence[str], None] = '11e31a447969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    user_role_enum = sa.Enum(
        "student", "company", "university",
        name="user_role_enum"
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)

    
    op.add_column('users', sa.Column('role', sa.Enum('STUDENT', 'COMPANY', 'UNIVERSITY', name='user_role_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
